---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ruler
  template:
    metadata:
      labels:
        name: ruler
    spec:
      containers:
      - name: ruler
        image: quay.io/cortexproject/cortex:v1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: cassandra-ip-config
        args:
        - -target=ruler
        - -log.level=debug
        - -server.http-listen-port=80
        - -ruler.configs.url=http://configs.default.svc.cluster.local:80
        - -ruler.alertmanager-url=http://alertmanager.default.svc.cluster.local/api/prom/alertmanager/
        - -consul.hostname=consul.default.svc.cluster.local:8500
        - -cassandra.addresses=$(CASSANDRA_DB_IP_1)
        - -cassandra.keyspace=cortex
        - -cassandra.host-verification=false
        - -schema-config-file=/etc/cortex/schema.yaml
        - -store.chunks-cache.memcached.hostname=memcached.default.svc.cluster.local
        - -store.chunks-cache.memcached.timeout=100ms
        - -store.chunks-cache.memcached.service=memcached
        - -distributor.replication-factor=1
        - -experimental.ruler.enable-api=true
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
      volumes:
        - name: config-volume
          configMap:
            name: schema-config
        - name: config-volume
          configMap:
            name: default-config
