---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: table-manager
  template:
    metadata:
      labels:
        name: table-manager
        use_cassandra: true
    spec:
      containers:
      - name: table-manager
        image: quay.io/cortexproject/cortex:v1.0.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=table-manager
        - -server.http-listen-port=80
        - -schema-config-file=/etc/cortex/schema.yaml
        - -cassandra.keyspace=cortex
        - -cassandra.host-verification=false
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
      volumes:
        - name: config-volume
          configMap:
            name: schema-config
